Move configs to ts

diff --git a/bin/run-server-k8s b/bin/run-server-k8s
--- a/bin/run-server-k8s
+++ b/bin/run-server-k8s
@@ -35,6 +35,11 @@ if ! kubectl config use-context kind-llm-in-a-box; then
     exit 1
 fi
 
+if ! npx --prefix="${script_dir}/../cdk tool render prod "${script_dir}/../build/prod-manifests.yaml"; then
+    echo "Failed to render the prod deployment"
+    exit 1
+fi
+
 if ! kubectl apply -k "${script_dir}/../k8s/overlays/standalone"; then
     echo "Failed to create resources"
     exit 1
